blank_issues_enabled: false
contact_links:
  - name: "â‰ï¸ Unsure if this is a bug, suggestion or support request ğŸ‘‰ please open a discussion ğŸ‘ˆ"
    url: https://github.com/magit/transient/discussions/categories/triage
    about: Start a discussion without having to specify its kind upfront.
  - name: "ğŸ’• Please support my work on Transient and other Emacs projects"
    url: https://github.com/sponsors/tarsius
    about: Thanks! Any support helps. These donations from users are my only income.
  - name: "ğŸ’¡ Suggest a feature ğŸ‘‰ please open a discussion instead of an issue ğŸ‘ˆ"
    url: https://github.com/magit/transient/discussions/categories/ideas
    about: Start a discussion suggesting an improvement or a new feature.
  - name: "ğŸ†˜ Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please also consider supporting others.
  - name: "ğŸ†˜ Ask the maintainers for support ğŸ‘‰ please open a discussion ğŸ‘ˆ"
    url: https://github.com/magit/transient/discussions/categories/support
    about: Please keep in mind that our bandwidth is limited.
  - name: "â„¹ï¸ Transient FAQ"
    url: https://docs.magit.vc/transient/FAQ.html
    about: Others might have had the same question before.
  - name: "â„¹ï¸ Transient Manual"
    url: https://docs.magit.vc/transient
    about: The fine manual may also be of use.
